export const initialNotifications = [
  {
    id: "1",
    userId: "1",
    title: "Issue Status Updated",
    message: "Your pothole report #CR001 is now in progress",
    type: "status_update",
    issueId: "1",
    read: false,
    createdAt: new Date("2024-01-16T10:00:00Z"),
  },
  {
    id: "2",
    userId: "1",
    title: "Issue Resolved",
    message: "Water leak report #CR004 has been resolved",
    type: "resolution",
    issueId: "4",
    read: true,
    createdAt: new Date("2024-01-13T14:30:00Z"),
  },
];

export const initialAnalytics = {
  totalIssues: 156,
  resolvedIssues: 89,
  avgResolutionTime: 5.2,
  categoryBreakdown: {
    road: 45,
    garbage: 32,
    water: 28,
    electricity: 21,
    streetlight: 15,
    "public-safety": 8,
    parks: 4,
    drainage: 2,
    noise: 1,
    "air-quality": 0,
    "public-transport": 0,
  },
  monthlyTrends: [
    { month: "Jan", reported: 45, resolved: 32 },
    { month: "Feb", reported: 52, resolved: 41 },
    { month: "Mar", reported: 38, resolved: 35 },
    { month: "Apr", reported: 21, resolved: 18 },
  ],
  hotspots: [
    {
      location: "Khunti District",
      count: 23,
      coordinates: { lat: 23.0833, lng: 85.2833 },
    },
    {
      location: "Ranchi District",
      count: 18,
      coordinates: { lat: 23.3441, lng: 85.3096 },
    },
    {
      location: "Jamshedpur District",
      count: 12,
      coordinates: { lat: 22.8046, lng: 86.2029 },
    },
    {
      location: "Dhanbad District",
      count: 8,
      coordinates: { lat: 23.7957, lng: 86.4304 },
    },
  ],
};

export const initialIssues = [
  {
    id: "1",
    ticketId: "CR001",
    title: "Large Pothole on Main Street",
    description: "Deep pothole causing vehicle damage near the intersection of Main St and Oak Ave. Multiple cars have been affected.",
    category: "road",
    status: "in-progress",
    priority: "high",
    location: {
      address: "123 Main Street, Khunti",
      coordinates: { lat: 23.0833, lng: 85.2833 },
    },
    reportedBy: {
      id: "1",
      name: "Rajesh Kumar",
      email: "rajesh@example.com",
    },
    assignedTo: {
      id: "2",
      name: "Ramesh Gupta",
      department: "Road Maintenance",
    },
    images: ["https://c02.purpledshub.com/uploads/sites/41/2024/01/Pot-hole-in-middle-of-the-road.jpg?w=600&webp=1"],
    createdAt: new Date("2024-01-15T09:00:00Z"),
    updatedAt: new Date("2024-01-16T11:00:00Z"),
    upvotes: 12,
    comments: [
      {
        id: "1",
        userId: "2",
        userName: "Ramesh Gupta",
        text: "Crew has been dispatched. Repair scheduled for tomorrow morning.",
        timestamp: new Date("2024-01-16T11:00:00Z"),
        type: "admin",
      },
    ],
    estimatedResolution: new Date("2024-01-18T17:00:00Z"),
    aiDetectedCategory: "road",
    reportingMethod: "form",
    language: "en",
  },
  {
    id: "2",
    ticketId: "CR002",
    title: "Overflowing Garbage Bins",
    description: "Multiple garbage bins overflowing on Elm Street. Attracting pests and creating unsanitary conditions.",
    category: "garbage",
    status: "submitted",
    priority: "medium",
    location: {
      address: "456 Elm Street, Ranchi",
      coordinates: { lat: 23.3441, lng: 85.3096 },
    },
    reportedBy: {
      id: "3",
      name: "Sunita Patel",
      email: "sunita@example.com",
    },
    images: ["https://norcalco.wpenginepowered.com/wp-content/uploads/2020/05/overflowing-garbage.jpg"],
    createdAt: new Date("2024-01-17T08:30:00Z"),
    updatedAt: new Date("2024-01-17T08:30:00Z"),
    upvotes: 8,
    comments: [],
    aiDetectedCategory: "garbage",
    reportingMethod: "form",
    language: "en",
  },
  {
    id: "3",
    ticketId: "CR003",
    title: "Broken Street Light",
    description: "Street light out for over a week, creating safety concerns for pedestrians at night.",
    category: "streetlight",
    status: "verified",
    priority: "medium",
    location: {
      address: "789 Pine Avenue, Jamshedpur",
      coordinates: { lat: 22.8046, lng: 86.2029 },
    },
    reportedBy: {
      id: "4",
      name: "Vikram Rao",
      email: "vikram@example.com",
    },
    images: ["https://assets.telegraphindia.com/telegraph/23RanRMCLight3_192419.jpg"],
    createdAt: new Date("2024-01-14T19:00:00Z"),
    updatedAt: new Date("2024-01-15T10:00:00Z"),
    upvotes: 15,
    comments: [
      {
        id: "2",
        userId: "5",
        userName: "Meera Iyer",
        text: "I can confirm this is still not working. Very dark at night.",
        timestamp: new Date("2024-01-15T10:00:00Z"),
        type: "citizen",
      },
    ],
    aiDetectedCategory: "streetlight",
    reportingMethod: "form",
    language: "en",
  },
  {
    id: "4",
    ticketId: "CR004",
    title: "Water Main Leak",
    description: "Suspected water main leak causing flooding on the sidewalk and wasting water.",
    category: "water",
    status: "resolved",
    priority: "critical",
    location: {
      address: "321 Water Street, Dhanbad",
      coordinates: { lat: 23.7957, lng: 86.4304 },
    },
    reportedBy: {
      id: "6",
      name: "Arjun Mehta",
      email: "arjun@example.com",
    },
    assignedTo: {
      id: "7",
      name: "Emergency Response Team",
      department: "Water Department",
    },
    images: ["https://ritewayphoenix.com/wp-content/uploads/2023/10/pacmed-water-main-leak-1024x576.jpg"],
    createdAt: new Date("2024-01-12T11:00:00Z"),
    updatedAt: new Date("2024-01-13T16:00:00Z"),
    resolvedAt: new Date("2024-01-13T16:00:00Z"),
    upvotes: 23,
    comments: [
      {
        id: "3",
        userId: "7",
        userName: "Emergency Response Team",
        text: "Issue has been resolved. New valve installed and tested.",
        timestamp: new Date("2024-01-13T16:00:00Z"),
        type: "admin",
      },
    ],
    rating: 5,
    feedback: "Excellent response time and quality of work!",
    aiDetectedCategory: "water",
    reportingMethod: "form",
    language: "en",
  },
  {
    id: "5",
    ticketId: "CR005",
    title: "Emergency: Gas Leak Detected",
    description: "Strong gas smell detected near residential building. Immediate attention required.",
    category: "public-safety",
    status: "in-progress",
    priority: "emergency",
    location: {
      address: "555 Safety Lane, Khunti",
      coordinates: { lat: 23.0833, lng: 85.2833 },
    },
    reportedBy: {
      id: "8",
      name: "Emergency Reporter",
      email: "emergency@example.com",
    },
    assignedTo: {
      id: "9",
      name: "Emergency Response Unit",
      department: "Fire Department",
    },
    images: ["https://static.vecteezy.com/system/resources/thumbnails/006/739/443/small_2x/corrosion-rusty-through-socket-tube-steam-gas-leak-pipeline-photo.jpg"],
    createdAt: new Date("2024-01-18T12:00:00Z"),
    updatedAt: new Date("2024-01-18T12:30:00Z"),
    upvotes: 45,
    comments: [
      {
        id: "4",
        userId: "9",
        userName: "Emergency Response Unit",
        text: "Emergency crew dispatched immediately. Area being evacuated as precaution.",
        timestamp: new Date("2024-01-18T12:30:00Z"),
        type: "admin",
      },
    ],
    isEmergency: true,
    aiDetectedCategory: "public-safety",
    reportingMethod: "voice",
    language: "en",
  },
];

export const categoryImages = {
  road: "https://c02.purpledshub.com/uploads/sites/41/2024/01/Pot-hole-in-middle-of-the-road.jpg?w=600&webp=1",
  garbage: "https://norcalco.wpenginepowered.com/wp-content/uploads/2020/05/overflowing-garbage.jpg",
  water: "https://ritewayphoenix.com/wp-content/uploads/2023/10/pacmed-water-main-leak-1024x576.jpg",
  electricity: "https://images.unsplash.com/photo-1509395176047-4a66953fd231",
  "public-safety": "https://images.unsplash.com/photo-1531938711058-49f5d4f58e41",
  parks: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
  drainage: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac",
   streetlight: "https://assets.telegraphindia.com/telegraph/23RanRMCLight3_192419.jpg",
  noise: "https://images.unsplash.com/photo-1519669556878-63bd7c2b2f5a",
  "air-quality": "https://images.unsplash.com/photo-1528680260893-5fbdc266f531",
  "public-transport": "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
};
